version: '3.7'

services:
    app:
        container_name: auth-service-container
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        image: auth-service
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./dist:/usr/src/auth-service/dist
        environment:
            NODE_ENV: production
            PORT: 3000
            MONGO_URL: mongodb://mongodb:27017/auth-service
        command: sh -c "npm run start:prod"
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        container_name: mongo-container
        image: mongo:latest
        restart: always
        ports:
          - '27017:27017'
        volumes:
          - mongo_dbv:/data/db
volumes:
    mongo_dbv:
