version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        command: sh -c "npm run start:prod"
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/app
            - /usr/src/app/node_modules
        environment:
            NODE_ENV: production
            PORT: 3000
            MONGO_URL: mongodb://mongodb-myapp:27017/auth-service
        container_name: auth-service-app
        depends_on:
            - mongodb-myapp
    mongodb-myapp:
        container_name: mongo_container
        image: mongo:latest
        restart: always
        ports:
          - '27017:27017'
        volumes:
          - mongo_dbv:/data/db
volumes:
    mongo_dbv:
